name: Prettier

on:
  push:
    branches:
      - main  # change to your default branch if different
      - develop  # add other branches as needed
  pull_request:
    branches:
      - main  # change to your default branch if different
      - develop  # add other branches as needed

jobs:
  prettier-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # adjust to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run Prettier check
      run: npm run format:check

  prettier-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # adjust to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run Prettier format
      run: npm run format
